# Generated by Django 2.1.7 on 2019-06-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='gallery/images')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'MCFC Gallery',
            },
        ),
    ]
