# Generated by Django 2.1.7 on 2019-06-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='member/images')),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Member List',
            },
        ),
    ]
