# Generated by Django 2.1.7 on 2019-06-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.ImageField(default='media/member/images/propic.png', upload_to='member/images'),
        ),
    ]
