# Generated by Django 2.1.7 on 2019-06-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20190602_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.ImageField(default='member/images/propic.png', upload_to='member/images'),
        ),
    ]
