# Generated by Django 2.1.7 on 2019-06-02 08:25

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20190602_0752'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='members',
            managers=[
                ('Member_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
