# Generated by Django 2.1.7 on 2019-06-03 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20190602_0825'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='members',
            managers=[
            ],
        ),
    ]
