# Generated by Django 2.1.7 on 2019-06-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20190603_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='member_type',
            field=models.CharField(choices=[(1, 'International'), (2, 'National')], default=1, max_length=10),
        ),
    ]
