# Generated by Django 2.1.7 on 2019-06-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_members_member_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='url_height',
            field=models.PositiveIntegerField(default=400),
        ),
        migrations.AddField(
            model_name='members',
            name='url_width',
            field=models.PositiveIntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.ImageField(default='member/images/propic.png', height_field=models.PositiveIntegerField(default=400), upload_to='member/images', width_field=models.PositiveIntegerField(default=400)),
        ),
        migrations.AlterField(
            model_name='members',
            name='member_type',
            field=models.IntegerField(choices=[(1, 'International'), (2, 'National')], default=1),
        ),
    ]
