# Generated by Django 2.1.7 on 2019-06-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='events',
            managers=[
            ],
        ),
    ]
